# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aws_batch_adhoc',
                'doc_host': 'https://JRSR92.github.io',
                'git_url': 'https://github.com/JRSR92/aws_batch_adhoc',
                'lib_path': 'aws_batch_adhoc'},
  'syms': {'aws_batch_adhoc.core': {'aws_batch_adhoc.core.foo': ('core.html#foo', 'aws_batch_adhoc/core.py')}}}